"""Generate ``<campaign_dir>/warm_restart.sh`` for operator convenience.

The script is a thin wrapper around ``primus-turbo-optimize -s <id>`` that:

1. Burns the campaign_id and the three filesystem roots into the script
   body, so the operator doesn't have to remember them across shell
   sessions or container restarts.
2. Requires the operator to supply ``-i / --iterations`` and/or
   ``-d / --duration``. The previous values were consumed by the
   terminated run; reusing them would immediately re-trigger
   TERMINATION_CHECK (T3 / T4) before the first new round executes.
3. Forwards any trailing args verbatim so flags like ``--debug-retry 5``
   or ``-v`` still work.

The script is regenerated at campaign start (via
``campaign.run_campaign``) and at the end of ``_phase_define_target``, so
the absolute paths it hard-codes always match the currently resolved
layout; operators can run it from any cwd.
"""

from __future__ import annotations

import logging
import shlex
import stat
from datetime import datetime
from pathlib import Path

from turbo_optimize.config import CampaignParams


log = logging.getLogger(__name__)


SCRIPT_NAME = "warm_restart.sh"


def write_script(params: CampaignParams) -> Path | None:
    """Write ``<campaign_dir>/warm_restart.sh``. Idempotent.

    Returns the path that was written, or ``None`` when ``campaign_dir``
    / ``campaign_id`` isn't known yet (brand-new campaign before
    DEFINE_TARGET has run ``ensure_campaign_dir``).
    """
    if params.campaign_dir is None or params.campaign_id is None:
        return None
    path = params.campaign_dir / SCRIPT_NAME
    body = _render(params)
    try:
        path.write_text(body, encoding="utf-8")
        mode = path.stat().st_mode
        path.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    except OSError as exc:
        log.warning("could not write %s: %s", path, exc)
        return None
    log.info("warm-restart script written to %s", path)
    return path


def _render(params: CampaignParams) -> str:
    assert params.campaign_id is not None
    assert params.campaign_dir is not None
    ts = datetime.now().strftime("%Y-%m-%d %H:%M")
    return (
        _TEMPLATE
        .replace("__GENERATED_AT__", ts)
        .replace("__CAMPAIGN_ID__", shlex.quote(params.campaign_id))
        .replace("__WORKSPACE_ROOT__", shlex.quote(str(params.workspace_root)))
        .replace("__SKILLS_ROOT__", shlex.quote(str(params.skills_root)))
        .replace("__STATE_DIR__", shlex.quote(str(params.state_dir)))
    )


_TEMPLATE = """\
#!/usr/bin/env bash
# Warm-restart this campaign.
#
# Generated by primus-turbo-optimize on __GENERATED_AT__. Safe to re-run;
# the orchestrator rewrites this file on every campaign start.
#
# You MUST re-specify -i / --iterations and/or -d / --duration: the
# previous values were already consumed by the prior run and would
# immediately re-trigger TERMINATION_CHECK (T3 / T4) if reused verbatim.

set -euo pipefail

CAMPAIGN_ID=__CAMPAIGN_ID__
WORKSPACE_ROOT=__WORKSPACE_ROOT__
SKILLS_ROOT=__SKILLS_ROOT__
STATE_DIR=__STATE_DIR__

usage() {
  cat <<EOF
usage: $(basename "$0") [-i N] [-d 2h] [-- extra args forwarded]

Resume campaign "$CAMPAIGN_ID".

Flags:
  -i, --iterations N   override max_iterations for the upcoming rounds
  -d, --duration D     override max_duration (e.g. "4h", "90m")
  -h, --help           show this message

At least one of -i / -d is required: reusing the previous values would
re-trigger termination before the first new round.

Anything after a literal "--" is forwarded verbatim to
primus-turbo-optimize, e.g.:

    ./warm_restart.sh -i 10 -d 4h -- --debug-retry 5 -v
EOF
}

ITER=""
DUR=""
EXTRA=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    -i|--iterations) ITER="${2:-}"; shift 2;;
    -d|--duration)   DUR="${2:-}";  shift 2;;
    -h|--help)       usage; exit 0;;
    --)              shift; EXTRA+=("$@"); break;;
    *)               EXTRA+=("$1"); shift;;
  esac
done

if [[ -z "$ITER" && -z "$DUR" ]]; then
  echo "ERROR: supply at least one of -i / -d" >&2
  echo >&2
  usage >&2
  exit 2
fi

cmd=(primus-turbo-optimize -s "$CAMPAIGN_ID"
     --workspace-root "$WORKSPACE_ROOT"
     --skills-root "$SKILLS_ROOT"
     --state-dir "$STATE_DIR")
[[ -n "$ITER" ]] && cmd+=(--max-iterations "$ITER")
[[ -n "$DUR"  ]] && cmd+=(--max-duration  "$DUR")

echo "+ ${cmd[*]} ${EXTRA[*]}"
exec "${cmd[@]}" "${EXTRA[@]}"
"""
